"""empty message

Revision ID: ea5c02356414
Revises: 2be8f95fc08c
Create Date: 2025-11-28 19:10:48.847962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5c02356414'
down_revision = '2be8f95fc08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refinements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('after_content', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refinements', schema=None) as batch_op:
        batch_op.drop_column('after_content')
        batch_op.drop_column('before_content')

    # ### end Alembic commands ###
