"""empty message

Revision ID: f82780c88fbf
Revises: bb17aa488bf8
Create Date: 2025-11-30 16:46:24.196144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82780c88fbf'
down_revision = 'bb17aa488bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refinements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refinements', schema=None) as batch_op:
        batch_op.drop_column('model')

    # ### end Alembic commands ###
